# Generated by Django 5.0.1 on 2024-03-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterer',
            name='amount',
            field=models.IntegerField(default=0, help_text='The amount that needs to be paid to the caterer', verbose_name='Amount to be paid to caterer'),
        ),
        migrations.AddField(
            model_name='caterer',
            name='daily_charge',
            field=models.IntegerField(default=130, help_text='The amount that needs to be paid to the caterer', verbose_name='Daily Charge of the catere'),
        ),
    ]
